name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
            target: Win64

          - name: Android32
            os: ubuntu-latest
            target: Android32

          - name: Android64
            os: ubuntu-latest
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          sdk: v5.10.1
          target: ${{ matrix.config.target }}

  combine:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Combine Geode builds
        id: combine
        uses: geode-sdk/build-geode-mod/combine@main

      - name: Upload final Geode
        uses: actions/upload-artifact@v7
        with:
          name: Toasty-Window-Analyzer
          path: ${{ steps.combine.outputs.build-output }}
