name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
            target: Win64

          - name: Android32
            os: ubuntu-latest
            target: Android32

          - name: Android64
            os: ubuntu-latest
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          sdk: v5.10.1
          target: ${{ matrix.config.target }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.config.name }}
          path: build/**/*.geode

  combine:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: builds
          pattern: build-*
          merge-multiple: true

      - name: Combine into final .geode
        uses: geode-sdk/build-geode-mod/combine@main
        with:
          path: builds

      - name: Upload final .geode
        uses: actions/upload-artifact@v4
        with:
          name: Final Mod (.geode)
          path: "*.geode"
